### ISSUE TITLE
preventDefault() seems to not work on up and down arrows?

### ISSUE THREAD

**Issue by fcoppey** [lukeraymonddowning/whenipress#17]
I want to navigate a table with up and down arrows in safari. but can't seem to prevent default behaviour of arrows with usual preventDefault():

whenipress('ArrowDown').then(e => {
        e.preventDefault();
        document.getElementById(document.activeElement.id).nextElementSibling.focus()
    }
);

Am I doing something wrong?

**Comment by lukeraymonddowning** [comment]
Hi there @fcoppey!

I'm working atm but will take a look at this later.

**Comment by fcoppey** [comment]
Hi, same with space bar... what's the procedure to use e.preventDefault() in your script?

**Comment by lukeraymonddowning** [comment]
Sorry for my tardiness on this @fcoppey. I've just pushed `1.8.0` that supports this. You'll want to access it via the `nativeEvent` node:

```javascript
whenipress('ArrowDown').then(e => {
    e.nativeEvent.preventDefault();
    document.getElementById(document.activeElement.id).nextElementSibling.focus()
});
```

**Comment by fcoppey** [comment]
Thanks a lot. Really appreciate the time you spent updating your app.

On 27 Nov 2020, at 20:31, Luke Downing <notifications@github.com> wrote:

﻿

Sorry for my tardiness on this @fcoppey<https://github.com/fcoppey>. I've just pushed 1.8.0 that supports this. You'll want to access it via the nativeEvent node:

whenipress('ArrowDown').then(e => {
    e.nativeEvent.preventDefault();
    document.getElementById(document.activeElement.id).nextElementSibling.focus()
});
