### ISSUE TITLE
Modifier keys combined with normal keys

### ISSUE THREAD

**Issue by moklick** [lukeraymonddowning/whenipress#19]
Hey @lukeraymonddowning 

I am looking for key handler library and this one seems to be very promising :)

Maybe it's not supported or I am doing something wrong but this is not working (same for Shift):

```js
whenipress("Alt", "s")
  .then(() => console.log("press alt+s"))
  .whenReleased(() => console.log("release alt+s"));
```

It's only triggered once or not at all and the release hook is never triggered. I am using a Macbook Pro.

codesandbox: https://codesandbox.io/s/focused-forest-vdg1l?file=/src/index.js

**Comment by lukeraymonddowning** [comment]
Hi @moklick,

thanks for using whenipress!

I've tested and shift works fine, you just need to remember to use the uppercase version of the character because the shift key will modify it:

```javascript
whenipress("Shift", "S")
  .then(() => console.log("press shift+s"))
  .whenReleased(() => console.log("release shift+s"));
```

**Comment by lukeraymonddowning** [comment]
Please check out the following resource as to why Alt combos don't work:

https://www.w3schools.com/jsref/event_onkeypress.asp

Might be worth choosing a different modifier key.

**Comment by lukeraymonddowning** [comment]
I'm going to close this for now given the above information. Feel free to open it again.

**Comment by lukeraymonddowning** [comment]
Actually @moklick further to this, ignore my previous comment.

It doesn't work because alt modifies the S key. You can use the key code instead:

```javascript
whenipress("Alt", "KeyS")
  .then(() => console.log("press alt+s"))
  .whenReleased(() => console.log("release alt+s"));
```

This site is super useful for this kind of stuff: https://keycode.info

**Comment by moklick** [comment]
Thanks! I wasn't aware that it's possible to pass the code as well.
