### ISSUE TITLE
TypeScript type declaration file

### ISSUE THREAD

**Issue by geopic** [lukeraymonddowning/whenipress#4]
I found your library from Reddit. If you want I can write a TypeScript type declaration file for this library so that TS developers can utilise the type-checking feature of the language as they use `whenipress`. Let me know if you are interested.

**Comment by lukeraymonddowning** [comment]
I would be very interested in that 👍👌 I’ve had multiple comments requesting as much so TS support seems like an important feature.

**Comment by geopic** [comment]
Nice one. I'll start on it tomorrow morning :smile:
